/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import BusinessLayer.CustomerManneger;
import DataAccessLayer.DTOClasses.Customer;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class AddCustomer extends javax.swing.JFrame {
//
//    static AddDiet addDiet =new AddDiet();
//   static MakeAnOrder order1= new MakeAnOrder();
//   static AddMealForm mealForm = new  AddMealForm();
    CustomerManneger customerManneger = new CustomerManneger();
    Customer customer = new Customer();
     Home dietForm = new Home();
    /**
     * Creates new form AddCustomerForm
     */
    public AddCustomer() {
       // initComponents();
         try {
            initComponents();
            this.setLocationRelativeTo(null);
            URL resource = this.getClass().getResource("/Images/grape.png");
            BufferedImage image = ImageIO.read(resource);
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        AddCustomer = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        height = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        medicalCondition = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Name = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddMeal2 = new javax.swing.JButton();
        order2 = new javax.swing.JButton();
        AddDiet1 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1218, 657));
        setPreferredSize(new java.awt.Dimension(1218, 657));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, 30));

        phone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone.setBorder(null);
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 250, 30));

        jTextField2.setBackground(new java.awt.Color(36, 47, 65));
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 182, -1, 32));

        AddCustomer.setBackground(new java.awt.Color(110, 72, 170));
        AddCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddCustomer.setForeground(new java.awt.Color(36, 47, 65));
        AddCustomer.setText("Add Customer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 140, 30));

        age.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.setBorder(null);
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 250, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel4.setText("weight ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 220, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 250, 11));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 250, 10));

        height.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        height.setBorder(null);
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 220, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel7.setText("hight");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 220, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 220, 10));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel8.setText("address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 250, 23));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 220, 10));

        address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 250, 32));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, 40));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 220, 10));

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 80, 30));

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 80, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel10.setText("phone");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 250, 23));

        weight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight.setBorder(null);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 220, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel12.setText("Medical Condition");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 210, 30));

        medicalCondition.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        medicalCondition.setForeground(new java.awt.Color(110, 72, 170));
        medicalCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Diabetes", "Blood preasure" }));
        medicalCondition.setToolTipText("");
        medicalCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalConditionActionPerformed(evt);
            }
        });
        jPanel1.add(medicalCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 220, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel14.setText("e_mail");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 250, 23));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 250, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, 11));

        Name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setBorder(null);
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 249, 30));

        mail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mail.setBorder(null);
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 249, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Add a Customer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 130, 28));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hello beautiful eat healthy");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 28));

        AddMeal2.setBackground(new java.awt.Color(97, 212, 195));
        AddMeal2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddMeal2.setForeground(new java.awt.Color(255, 255, 255));
        AddMeal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info4.png"))); // NOI18N
        AddMeal2.setText("Add Meal");
        AddMeal2.setBorderPainted(false);
        AddMeal2.setContentAreaFilled(false);
        AddMeal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMeal2ActionPerformed(evt);
            }
        });
        jPanel2.add(AddMeal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));

        order2.setBackground(new java.awt.Color(97, 212, 195));
        order2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        order2.setForeground(new java.awt.Color(255, 255, 255));
        order2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        order2.setText("Order");
        order2.setBorder(null);
        order2.setBorderPainted(false);
        order2.setContentAreaFilled(false);
        order2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order2ActionPerformed(evt);
            }
        });
        jPanel2.add(order2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 40));

        AddDiet1.setBackground(new java.awt.Color(97, 212, 195));
        AddDiet1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddDiet1.setForeground(new java.awt.Color(255, 255, 255));
        AddDiet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info3.png"))); // NOI18N
        AddDiet1.setText("Add Diet");
        AddDiet1.setBorderPainted(false);
        AddDiet1.setContentAreaFilled(false);
        AddDiet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDiet1ActionPerformed(evt);
            }
        });
        jPanel2.add(AddDiet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 40));

        Home.setBackground(new java.awt.Color(97, 212, 195));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 520));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel15.setText("full name ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 90, 250, 28));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 250, 11));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 40, 820, 520);

        jPanel3.setBackground(new java.awt.Color(110, 72, 170));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1220, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        // TODO add your handling code here:
        
          if (Name == null ||Name.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer name");
            return;
        }
           if (mail == null ||mail.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer mail");
            return;
        }
         if (phone == null ||phone.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer phone");
            return;
        }  
          if (address == null ||address.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer address");
            return;
        }  
           if (height == null ||height.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer height");
            return;
        }  
            if (weight == null ||weight.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter customer weight");
            return;
        }  
            
        customer.setFulltName(Name.getText());
        customer.setE_mail(mail.getText());
        customer.setPhone(phone.getText());
        customer.setAddress(address.getText());
        try {
        double h= Double.parseDouble(height.getText());
        customer.setHeight(h);
        } 
        catch (NumberFormatException | NullPointerException nfe) {
           JOptionPane.showMessageDialog(null, "please enter numeric value for height");
           return;
        }
        try{
        double w =Double.parseDouble(weight.getText());
        customer.setWeight(w);}
         catch (NumberFormatException | NullPointerException nfe) {
           JOptionPane.showMessageDialog(null, "please enter numeric value for weight");
           return;
        }
        customer.setMedicalStatus(medicalCondition.getSelectedItem().toString());
        int Age = Integer.parseInt(age.getText());
        customer.setAge(Age);
        customerManneger.addCustomer(customer);
        JOptionPane.showMessageDialog(null, "New customer is Added");
        dietForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AddCustomerActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void medicalConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalConditionActionPerformed

    private void AddMeal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMeal2ActionPerformed
        // TODO add your handling code here:
        AddMealForm mealForm = new  AddMealForm();
        mealForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddMeal2ActionPerformed

    private void order2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order2ActionPerformed
        // TODO add your handling code here:
        MakeAnOrder order1= new MakeAnOrder();
        order1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_order2ActionPerformed

    private void AddDiet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDiet1ActionPerformed
        // TODO add your handling code here:
        AddDiet addDiet =new AddDiet();
        addDiet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddDiet1ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        dietForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer;
    private javax.swing.JButton AddDiet1;
    private javax.swing.JButton AddMeal2;
    private javax.swing.JButton Home;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> medicalCondition;
    private javax.swing.JButton order2;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
