/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import BusinessLayer.MealManneger;
import DataAccessLayer.DTOClasses.Diet;
import DataAccessLayer.DTOClasses.Meal;
import DataAccessLayer.Repositories.DietRepository;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Hp
 */
public class AddMealForm extends javax.swing.JFrame {
//    static AddCustomer addCustomer =new AddCustomer();
//   static AddDiet addDiet =new AddDiet();
//   static MakeAnOrder order1= new MakeAnOrder();
  
  
    DietRepository dietRepository = new DietRepository();
    Meal meal =new Meal();
   
    MealManneger mealManneger = new MealManneger();
    ArrayList<Diet> diets;   
    File selectedFile;
    /**
     * Creates new form AddMealForm
     */
    public AddMealForm() {
        //initComponents();
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            URL resource = this.getClass().getResource("/Images/grape.png");
            BufferedImage image = ImageIO.read(resource);
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         diets= dietRepository.GetAll();
         ArrayList<String>names=new ArrayList<>();
         for(Diet d : diets)
         {
             names.add(d.getName());
         }
         DietName.setModel(new DefaultComboBoxModel(names.toArray()));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        browes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DietName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingrediants = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        AddMeal = new javax.swing.JButton();
        type1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        order = new javax.swing.JButton();
        AddDiet = new javax.swing.JButton();
        AddCustomer = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Add a meal \\ drink");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 181, 28));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel5.setText("name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, 30));

        browes.setBackground(new java.awt.Color(110, 72, 170));
        browes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        browes.setText("Browes");
        browes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesActionPerformed(evt);
            }
        });
        jPanel1.add(browes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 120, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel4.setText("price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 168, 210, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 190, 11));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 190, 10));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel7.setText("ingredients");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 200, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel11.setText("Meal Type");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 30));

        DietName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DietName.setForeground(new java.awt.Color(110, 72, 170));
        DietName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Under weight", "over weight", "obese" }));
        DietName.setToolTipText("");
        DietName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DietNameActionPerformed(evt);
            }
        });
        jPanel1.add(DietName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 190, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel12.setText("image");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 220, 110));

        ingrediants.setColumns(20);
        ingrediants.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        ingrediants.setRows(5);
        ingrediants.setBorder(null);
        jScrollPane1.setViewportView(ingrediants);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 210, 100));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel8.setText("Diet name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 190, 30));

        AddMeal.setBackground(new java.awt.Color(110, 72, 170));
        AddMeal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddMeal.setText("Add");
        AddMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMealActionPerformed(evt);
            }
        });
        jPanel1.add(AddMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 90, 30));

        type1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        type1.setForeground(new java.awt.Color(110, 72, 170));
        type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Break fast", "Lunch", "Dinner", "Hot Drink", "Cold Drink" }));
        type1.setToolTipText("");
        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });
        jPanel1.add(type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 190, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello beautiful eat healthy");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 28));

        Home.setBackground(new java.awt.Color(97, 212, 195));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 40));

        order.setBackground(new java.awt.Color(97, 212, 195));
        order.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        order.setText("Order");
        order.setBorderPainted(false);
        order.setContentAreaFilled(false);
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel2.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 40));

        AddDiet.setBackground(new java.awt.Color(97, 212, 195));
        AddDiet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddDiet.setForeground(new java.awt.Color(255, 255, 255));
        AddDiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info3.png"))); // NOI18N
        AddDiet.setText("Add Diet");
        AddDiet.setBorderPainted(false);
        AddDiet.setContentAreaFilled(false);
        AddDiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDietActionPerformed(evt);
            }
        });
        jPanel2.add(AddDiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 40));

        AddCustomer.setBackground(new java.awt.Color(97, 212, 195));
        AddCustomer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        AddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info 5.png"))); // NOI18N
        AddCustomer.setText("Add Customer");
        AddCustomer.setBorderPainted(false);
        AddCustomer.setContentAreaFilled(false);
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, 30));

        price.setBorder(null);
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 730, 500));

        jPanel3.setBackground(new java.awt.Color(110, 72, 170));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int Dietid(){
    for (Diet diet:diets){
        String selectedItem=DietName.getSelectedItem().toString();
       if( diet.getName().equals(selectedItem))
           return diet.getID();
    }
    return 0;
    }
  
    private void browesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        FileFilter filter = new FileNameExtensionFilter("Image files",  ImageIO.getReaderFileSuffixes());
        jFileChooser.setFileFilter(filter);
		int returnValue = jFileChooser.showOpenDialog(null);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    selectedFile = jFileChooser.getSelectedFile();
                    jLabel12.setIcon((new ImageIcon(selectedFile.getAbsolutePath())));
		}
         
        
    }//GEN-LAST:event_browesActionPerformed

    private void DietNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DietNameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DietNameActionPerformed

    private void AddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMealActionPerformed
        try {
            // TODO add your handling code here:
             if (name == null ||name.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter meal name");
            return;
        }
            if (price == null || price.getText().length()== 0) {
            JOptionPane.showMessageDialog(null, "please enter phone number");
            return;
        }
            meal.setName(name.getText());
            try{
            double p= Double.parseDouble(price.getText());
            meal.setPrice((float)p);}
            catch (NumberFormatException | NullPointerException nfe) {
           JOptionPane.showMessageDialog(null, "please enter numeric value for price");
           return;
        }
            meal.setType(DietName.getSelectedItem().toString());
            meal.setIngredients(ingrediants.getText());
            meal.setDietID(Dietid());            
            byte [] image= Files.readAllBytes(selectedFile.toPath());           
            meal.setImage(image);
            mealManneger.addMeal(meal);
             JOptionPane.showMessageDialog(null, "New meals is Added");
              Home dietForm = new Home();
             dietForm.setVisible(true);
             this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AddMealForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddMealActionPerformed

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type1ActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
        MakeAnOrder order1= new MakeAnOrder();
        order1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_orderActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
         Home dietForm = new Home();
        dietForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void AddDietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDietActionPerformed
        // TODO add your handling code here:
        AddDiet addDiet =new AddDiet();
        addDiet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddDietActionPerformed

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer addCustomer =new AddCustomer();
        addCustomer.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_AddCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMealForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMealForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMealForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMealForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMealForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer;
    private javax.swing.JButton AddDiet;
    private javax.swing.JButton AddMeal;
    private javax.swing.JComboBox<String> DietName;
    private javax.swing.JButton Home;
    private javax.swing.JButton browes;
    private javax.swing.JTextArea ingrediants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField name;
    private javax.swing.JButton order;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> type1;
    // End of variables declaration//GEN-END:variables
}
